In [ ]:
import numpy as np


In [ ]:
arr0=np.array(5)
print("Zero_Dimension Array: \n",arr0)

Zero_Dimension Array: 
 5


In [ ]:
arr1 = np.array([1, 2, 3])
print("One_Dimension Array: \n",arr1)

One_Dimension Array: 
 [1 2 3]


In [ ]:
arr2 = np.array([[1, 2, 3],[4, 5, 6]])
print("Two Dimensional Array: \n", arr2)


Two Dimensional Array: 
 [[1 2 3]
 [4 5 6]]


In [ ]:
arr3= np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("Three Dimensional Array: \n", arr3)


Three Dimensional Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr4= np.array([[1, 2, 3],[4, 5, 6],[7,8,9],[10,11,12]])
print("Four Dimensional Array: \n", arr4)


Three Dimensional Array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr5= np.array([[1, 2, 3],[4, 5, 6],[7,8,9],[10,11,12],[13,14,15]])
print("Five Dimensional Array: \n", arr5)


Five Dimensional Array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
