In [ ]:
import numpy as npy


In [ ]:
arr1 = npy.array([1, 2, 3])
print("Array: \n",arr1)
arr2 = npy.array([1, 2, 3])
print("Array: \n",arr2)
arr3=arr1+arr2

print("Sum: \n",arr3)
arry = npy.array([[1, 2, 3],[4, 5, 6]])
print("Array: \n", arry)


Array: 
 [1 2 3]
Array: 
 [1 2 3]
Sum: 
 [2 4 6]
Array: 
 [[1 2 3]
 [4 5 6]]
